on: 
  issue_comment:
    types: [created]
name: Rebase and Merge
jobs:
  rebase_and_merge:
    name: RebaseAndMerge
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/merge')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      id: rebase_step
      uses: cirrus-actions/rebase@1.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/github-script@v3.0.0
      with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              repo: context.repo.repo,
              labels: ['issue:rebase conflicts']
            })
    - name: GitHub merge Script
      if: success()
      uses: actions/github-script@v3.0.0
      with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            if ('${{ contains(github.event.pull_request.labels.*.name, 'issue:rebase conflicts') }}' == 'true') {
              github.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                name: 'issue:rebase conflicts'
              })
            }
            await github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.issue.number,
              merge_method: 'merge'
            })

