on:
  pull_request:
    types:
      - labeled
name: Rebase and Merge
jobs:
  rebase_and_merge:
    name: RebaseAndMerge
    if: github.event.label.name == 'RebaseAndMerge'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.3.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Failure Label
      uses: actions/github-script@v3.0.0
      if: ${{ failure() }}
      with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            github.issues.removeLabel({
              owner: context.repo.owner,
              issue_number: context.issue.number,
              repo: context.repo.repo,
              name: 'RebaseAndMerge'
            })
            github.issues.addLabels({
              owner: context.repo.owner,
              issue_number: context.issue.number,
              repo: context.repo.repo,
              labels: ['issue:rebase conflicts']
            })
    - name: Merge
      uses: actions/github-script@v3.0.0
      if: success()
      with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            if ('${{ contains(github.event.pull_request.labels.*.name, 'issue:rebase conflicts') }}' == 'true') {
              github.issues.removeLabel({
                owner: context.repo.owner,
                issue_number: context.issue.number,
                repo: context.repo.repo,
                name: 'issue:rebase conflicts'
              })
            }
            github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: 'merge'
            })

